SELECT NULLIF([patient_id], '') AS [Patient ID] --- The NULLIF was used to return our blank cells as NULL. If I didn't use the NULL, we would have Cholesterol, Heart Rtae, etc, as zeros, which is medically impossible.
      --,[resting_ecg]
      ,NULLIF([age], '') AS [Age]
      ,NULLIF([gender],'') AS [Gender]
      --,[chest_pain_type]
      ,CAST(CAST(NULLIF([resting_bp], '') AS FLOAT) AS INT) AS [Resting BP]  --I used the double cast because my data type was saved as float and I need it in Integer format.
      ,CAST(CAST(NULLIF([cholesterol], '') AS FLOAT) AS INT) AS [Cholesterol]
      ,CAST(CAST(NULLIF([fasting_blood_sugar], '') AS FLOAT) AS INT) AS [Fasting Blood Sugar]
      ,CAST(CAST(NULLIF([max_heart_rate], '') AS FLOAT) AS INT) AS [Max Heart Rate]
      --,[exercise_angina]
      ,NULLIF([oldpeak],'') AS [ST Depression Old Peak]
      --,[st_slope]
      --,[num_major_vessels]
      --,[thalassemia]
      ,NULLIF([bmi],'') AS [BMI]
      ,NULLIF([smoking_status],'') AS [Smoking Status]
      ,NULLIF([alcohol_consumption],'') as [Alcohol Consumption]
      ,NULLIF([physical_activity],'') AS [Physical Activity]
      ,NULLIF([family_history],'') AS [Family History]
      ,NULLIF([diabetes], '') AS [Diabetes]
      ,CAST(CAST(NULLIF([stress_level], '') AS FLOAT) AS INT) AS [Stress Level]
      ,[heart_attack_risk] AS [Heart Attack Risk]
  FROM [AdventureWorksDW2019].[dbo].[RawHeartAttackData]
